# -*- coding: utf-8 -*-
"""viva_project_groq

Automatically generated by Colab.


"""

# ==============================================================================
# ⚙️ EXAMINER VIVA CONFIGURATIONS
# ------------------------------------------------------------------------------
# Faculty-specific settings (subject, difficulty, time limit, question count)
# now live in the separate viva_config.py file next to this script — that is
# the ONLY file another faculty member needs to edit to reuse this app for
# their own subject. See viva_config.py for instructions. The try/except
# below just keeps this script working with sensible defaults if that file
# is ever missing.
# ==============================================================================
try:
    from viva_config import (
        VIVA_SUBJECT,
        VIVA_DIFFICULTY,
        VIVA_TOTAL_QUESTIONS,
        VIVA_TIME_LIMIT_MINUTES,
        AVAILABLE_SUBJECTS,
        VIVA_CUSTOM_INSTRUCTIONS,
        VIVA_MANDATORY_QUESTIONS,
    )
except ImportError:
    VIVA_SUBJECT = "Organizational Behaviour"
    VIVA_DIFFICULTY = "Standard"
    VIVA_TOTAL_QUESTIONS = 10
    VIVA_TIME_LIMIT_MINUTES = 10
    AVAILABLE_SUBJECTS = [
        "Marketing Management",
        "Financial Management",
        "Human Resource Management",
        "Organizational Behaviour",
        "Organizational Behaviour 2",
        "Business Strategy",
    ]
    VIVA_CUSTOM_INSTRUCTIONS = ""
    VIVA_MANDATORY_QUESTIONS = []
# ==============================================================================

import streamlit as st
import streamlit.components.v1 as components
from groq import Groq
import fitz
from docx import Document
import io
import re
import time
from datetime import datetime
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
import os
import requests
import json
import random
import uuid
from filelock import FileLock, Timeout as FileLockTimeout

st.set_page_config(page_title="GLIM Project Viva Examiner", page_icon="🎓")
st.title("🎓 GLIM Project Viva Examiner")
st.caption("Powered by Groq + GPT-OSS 20B — 🎙️ Web-Enabled Oral Viva Mode")

# Save the scoresheet in the SAME folder as this script, regardless of where
# Streamlit is launched from. This makes it easy to find on disk.
try:
    _SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
except NameError:
    # __file__ isn't defined in some interactive contexts (e.g. Jupyter); fall back to cwd
    _SCRIPT_DIR = os.getcwd()
SCORESHEET_FILE = os.path.join(_SCRIPT_DIR, "GLIM_Viva_Scores.xlsx")
# Every student's session shares this ONE file. Without a lock, two students
# finishing at nearly the same moment can both load the workbook, append
# their row in memory, and save — the second save silently overwrites the
# first (lost row), or a save landing mid-read produces a corrupted
# .xlsx that fails to open for every student after that. The lock file
# below serializes access so saves queue up safely instead of colliding.
SCORESHEET_LOCK = SCORESHEET_FILE + ".lock"

# Component directory for the dynamic timer and cheat monitor.
#
# IMPORTANT: this must be UNIQUE PER STUDENT SESSION, not one shared folder.
# render_viva_controller() rewrites index.html on every rerun with THAT
# session's remaining_seconds, then serves it via declare_component(). If
# every session pointed at the same folder/name (as this used to), two
# students answering around the same moment could each load the OTHER's
# countdown, or catch the file mid-write and get a broken/blank timer and
# anti-cheat panel. A per-session id keeps every student's file (and the
# component's internal registration) fully isolated from every other
# student's, while still being reused across that one student's own reruns.
if "component_session_id" not in st.session_state:
    st.session_state.component_session_id = uuid.uuid4().hex
COMPONENT_SESSION_ID = st.session_state.component_session_id
COMPONENT_DIR = os.path.join(_SCRIPT_DIR, "viva_controller_component", COMPONENT_SESSION_ID)
# exist_ok=True avoids a FileExistsError race: on Streamlit Cloud, two
# students' sessions can both hit this startup code within the same
# instant, and one can create the folder in the gap between the other's
# os.path.exists() check and its os.makedirs() call.
os.makedirs(COMPONENT_DIR, exist_ok=True)

# --- Dynamic HTML/JS Controller Component ---
def render_viva_controller(remaining_seconds):
    html_code = f"""<!DOCTYPE html>
<html>
<head>
    <style>
        .timer-box {{
            font-family: 'Arial', sans-serif;
            background: #ffebee; color: #c62828;
            padding: 12px; border-radius: 8px; border: 1px solid #ffcdd2;
            text-align: center; margin-bottom: 15px; font-weight: bold;
        }}
        .timer-label {{
            font-size: 10px; text-transform: uppercase; letter-spacing: 1px;
            color: #b71c1c; margin-bottom: 4px;
        }}
        .timer-value {{ font-size: 22px; }}
        .fs-box {{
            font-family: 'Arial', sans-serif; background: #fff8e1;
            border: 1px solid #ffe082; border-radius: 8px; padding: 10px;
            text-align: center; margin-bottom: 15px;
        }}
        .fs-warn {{ font-size: 11px; color: #e65100; margin-bottom: 6px; }}
        .fs-btn {{
            background: #e65100; color: #fff; border: none; border-radius: 6px;
            padding: 8px 14px; font-weight: bold; font-size: 13px;
            cursor: pointer; width: 100%;
        }}
    </style>
    <script>
    // ---- Streamlit component handshake (REQUIRED) -------------------------
    function _post(type, data) {{
        window.parent.postMessage(Object.assign({{isStreamlitMessage: true, type: type}}, data), "*");
    }}
    function sendValue(value) {{
        _post("streamlit:setComponentValue", {{value: value, dataType: "json"}});
    }}
    _post("streamlit:componentReady", {{apiVersion: 1}});
    _post("streamlit:setFrameHeight", {{height: 150}});

    let timeLeft = {remaining_seconds};
    function updateTimerDisplay() {{
        let m = Math.floor(timeLeft / 60);
        let s = timeLeft % 60;
        if (s < 10) s = "0" + s;
        let el = document.getElementById("timer");
        if (el) el.innerText = m + ":" + s;
        if (timeLeft < 60) {{
            let c = document.getElementById("timer-container");
            if (c) c.style.background = "#ffcdd2";
        }}
    }}
    let timerInterval = setInterval(function() {{
        timeLeft--;
        if (timeLeft <= 0) {{ clearInterval(timerInterval); sendValue("timeout"); }}
        else {{ updateTimerDisplay(); }}
    }}, 1000);

    // ---- ANTI-CHEAT / EXAM LOCK-DOWN -------------------------------------
    let cheatReported = false;
    function reportCheat(reason) {{
        if (cheatReported) return;
        cheatReported = true;
        try {{ console.warn("VIVA cheat trigger: " + reason); }} catch (e) {{}}
        sendValue("cheated");
    }}
    let guardWin, guardDoc;
    try {{ guardWin = window.top; guardDoc = window.top.document; void guardDoc.visibilityState; }}
    catch (e) {{ guardWin = window; guardDoc = document; }}
    document.addEventListener('visibilitychange', function() {{
        if (document.visibilityState === 'hidden') reportCheat("tab hidden / minimized");
    }});
    try {{
        guardDoc.addEventListener('visibilitychange', function() {{
            if (guardDoc.visibilityState === 'hidden') reportCheat("tab hidden (top)");
        }});
    }} catch (e) {{}}
    window.addEventListener('blur', function() {{ reportCheat("focus lost / another window opened"); }});
    try {{ guardWin.addEventListener('blur', function() {{ reportCheat("focus lost (top)"); }}); }} catch (e) {{}}
    try {{
        guardDoc.addEventListener('contextmenu', function(e) {{ e.preventDefault(); }});
        ['copy','cut','paste'].forEach(function(ev) {{
            guardDoc.addEventListener(ev, function(e) {{ e.preventDefault(); }});
        }});
    }} catch (e) {{}}
    function keyGuard(e) {{
        let k = (e.key || "").toLowerCase();
        let cmd = e.ctrlKey || e.metaKey;
        if (cmd && ['t','n','w','tab'].indexOf(k) !== -1) {{
            e.preventDefault(); reportCheat("blocked new-window/tab shortcut: " + k);
        }}
        if (k === 'f12' || (cmd && e.shiftKey && ['i','j','c'].indexOf(k) !== -1) || (cmd && k === 'u')) {{
            e.preventDefault(); reportCheat("blocked dev-tools / view-source");
        }}
    }}
    window.addEventListener('keydown', keyGuard, true);
    try {{ guardWin.addEventListener('keydown', keyGuard, true); }} catch (e) {{}}
    try {{ guardWin.addEventListener('beforeunload', function(e) {{ e.preventDefault(); e.returnValue = ""; }}); }} catch (e) {{}}
    function isFullscreen() {{
        try {{ return !!(guardDoc.fullscreenElement || guardDoc.webkitFullscreenElement); }}
        catch (e) {{ return !!(document.fullscreenElement); }}
    }}
    function syncFullscreenUI() {{
        let box = document.getElementById("fs-box");
        if (box) box.style.display = isFullscreen() ? "none" : "block";
    }}
    function enterFullscreen() {{
        try {{
            let el = guardDoc.documentElement;
            let req = el.requestFullscreen || el.webkitRequestFullscreen;
            if (req) {{ req.call(el); try {{ guardWin.__vivaFS = true; }} catch (e) {{}} }}
        }} catch (e) {{}}
    }}
    function fsChange() {{
        let entered = false;
        try {{ entered = !!guardWin.__vivaFS; }} catch (e) {{}}
        if (!isFullscreen() && entered) reportCheat("exited fullscreen during exam");
        syncFullscreenUI();
    }}
    try {{ guardDoc.addEventListener('fullscreenchange', fsChange); }} catch (e) {{}}
    document.addEventListener('fullscreenchange', fsChange);
    window.addEventListener("load", function() {{
        updateTimerDisplay();
        let btn = document.getElementById("fs-btn");
        if (btn) btn.addEventListener("click", enterFullscreen);
        syncFullscreenUI();
    }});
    </script>
</head>
<body style="margin:0; padding:0; background:transparent;">
    <div id="fs-box" class="fs-box" style="display:none;">
        <div class="fs-warn">WARNING: This viva must run in fullscreen.<br>Exiting fullscreen will submit your exam.</div>
        <button id="fs-btn" class="fs-btn">Enter Fullscreen to continue</button>
    </div>
    <div id="timer-container" class="timer-box">
        <div class="timer-label">Time Remaining</div>
        <div id="timer" class="timer-value">--:--</div>
    </div>
</body>
</html>
"""
    with open(os.path.join(COMPONENT_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(html_code)

    focus_monitor = components.declare_component(
        f"viva_controller_{COMPONENT_SESSION_ID}", path=COMPONENT_DIR
    )
    return focus_monitor(key="viva_control_instance")

# --- Groq client ---
client = Groq(api_key=st.secrets.get("GROQ_API_KEY") or os.environ.get("GROQ_API_KEY"))

def chat_with_llm(messages, max_retries=4):
    """Calls the Groq API, retrying transient/rate-limit errors with backoff.

    During a live exam, many students share ONE Groq API key, so bursts of
    simultaneous questions can trip the free-tier rate limit (HTTP 429) or
    hit a brief timeout/5xx. Without retrying, that surfaces as a raw
    traceback and crashes the student's session. Instead we back off and
    retry a few times, and only give up (with a friendly message) if the
    problem persists.
    """
    last_error = None
    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model="openai/gpt-oss-20b",
                messages=messages,
                max_tokens=1024,
                # "medium" balances speed with reliably following instructions like
                # "ask ONE question at a time" — "low" was faster but let the model
                # bundle multiple questions into a single reply more often. Bump to
                # "high" for even more careful, deliberate questioning at the cost
                # of extra latency; drop back to "low" only if replies feel slow.
                reasoning_effort="medium",
            )
            return response.choices[0].message.content
        except Exception as e:
            last_error = e
            msg = str(e).lower()
            is_transient = any(tok in msg for tok in
                                ["429", "rate limit", "rate_limit", "timeout",
                                 "timed out", "502", "503", "connection"])
            if is_transient and attempt < max_retries - 1:
                # Exponential backoff with jitter so multiple students' retries
                # don't all land on the same instant and re-collide.
                wait = (2 ** attempt) + random.uniform(0, 1)
                time.sleep(wait)
                continue
            break

    st.error(
        "⚠️ The examiner AI is temporarily busy (likely many students using "
        "the same API key at once). Please wait a few seconds, then submit "
        "your answer again — nothing has been lost."
    )
    return None

# --- Save to Google Sheets via Webhook ---
def save_to_google_sheets(student_name, student_roll, student_email, subject, difficulty, score,
                          grade, strengths, improvements, exchanges, project_name):
    webhook_url = st.secrets.get("GSHEETS_WEBHOOK_URL") or os.environ.get("GSHEETS_WEBHOOK_URL")
    if not webhook_url:
        st.error("Google Sheets NOT saved: the GSHEETS_WEBHOOK_URL secret is missing or empty. "
                 "In Streamlit -> Settings -> Secrets add a line exactly like:  "
                 'GSHEETS_WEBHOOK_URL = "https://script.google.com/macros/s/XXX/exec"  '
                 "then Save and Reboot.")
        return False
    if not str(webhook_url).strip().endswith("/exec"):
        st.warning("Your GSHEETS_WEBHOOK_URL does not end in /exec. Use the Apps Script Web App "
                   "URL from Deploy -> Web app, not the editor or /dev URL.")
        
    payload = {
        "student_email": student_email,
        "student_roll": student_roll,
        "student_email": student_email,
        "subject": subject,
        "difficulty": difficulty,
        "project_name": project_name,
        "score": score,
        "grade": grade,
        "exchanges": exchanges,
        "strengths": strengths,
        "improvements": improvements
    }
    
    try:
        response = requests.post(webhook_url, json=payload, timeout=15)
        if response.status_code == 200 and "Success" in response.text:
            return True
        else:
            st.warning("Google Sheets did not accept the data (HTTP "
                       + str(response.status_code) + "). Response start: "
                       + str(response.text)[:300]
                       + "  ->  Most likely the Apps Script Web App access is not set to "
                       "'Anyone', or you edited the script without deploying a NEW version.")
            return False
    except Exception as e:
        st.error(f"⚠️ Failed to write to Google Sheets: {e}")
        return False

# --- Extract text from uploaded file ---
def extract_text(uploaded_file):
    text = ""
    if uploaded_file.name.endswith(".pdf"):
        pdf_bytes = uploaded_file.read()
        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        for page in doc:
            text += page.get_text()
    elif uploaded_file.name.endswith(".docx"):
        doc = Document(io.BytesIO(uploaded_file.read()))
        for para in doc.paragraphs:
            text += para.text + "\n"
    return text.strip()

def truncate(text, max_chars=6000):
    if len(text) > max_chars:
        return text[:max_chars] + "\n\n[... project continues ...]"
    return text

# --- Parse score from closing message ---
def parse_score(text):
    """Try a series of regex patterns to pull a 0-10 score out of the LLM reply.
    The patterns are tried in order — most specific first."""
    if not text:
        return None
    # Strip markdown emphasis (*, **) so they don't trip up the regex
    cleaned = re.sub(r'[\*_`]', '', text)

    patterns = [
        # "Score: 7/10" or "Score - 7.5 / 10"
        r'score\s*[:\-]?\s*(\d+(?:\.\d+)?)\s*/\s*10',
        # "Final score: 7" or "Overall score 7.5"
        r'(?:final|overall)?\s*score\s*[:\-]?\s*(\d+(?:\.\d+)?)\b',
        # "7/10" or "7.5 / 10" anywhere in the text
        r'\b(\d+(?:\.\d+)?)\s*/\s*10\b',
        # "7 out of 10"
        r'\b(\d+(?:\.\d+)?)\s+out\s+of\s+10\b',
        # "I would give this an 8"
        r'(?:give|rate|award)\s+(?:this|you|the\s+student)?\s*(?:an?\s+)?(\d+(?:\.\d+)?)\s*(?:/\s*10)?',
    ]
    for pattern in patterns:
        match = re.search(pattern, cleaned, re.IGNORECASE)
        if match:
            try:
                value = float(match.group(1))
                # sanity check: must be a plausible 0-10 mark
                if 0 <= value <= 10:
                    return value
            except ValueError:
                continue
    return None

# --- Parse strengths and improvements ---
def parse_feedback(text):
    strengths, improvements = "", ""
    s = re.search(
        r'strength[s]?[:\-\*\s]+(.*?)(?=area|improvement|weakness|recommend|$)',
        text, re.IGNORECASE | re.DOTALL)
    if s:
        strengths = s.group(1).strip()[:300]
    i = re.search(
        r'(?:area[s]? (?:for|needing)|improvement[s]?|weakness)[:\-\*\s]+(.*?)(?=recommend|suggest|$)',
        text, re.IGNORECASE | re.DOTALL)
    if i:
        improvements = i.group(1).strip()[:300]
    return strengths, improvements

# --- Save to Excel ---
def save_to_excel(student_name, student_roll, student_email, subject, difficulty, score,
                  grade, strengths, improvements, exchanges, project_name):

    thin = Side(style='thin')
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    header_font = Font(name='Arial', bold=True, color='FFFFFF', size=11)
    header_fill = PatternFill('solid', start_color='1F4E79')
    center = Alignment(horizontal='center', vertical='center', wrap_text=True)
    left = Alignment(horizontal='left', vertical='center', wrap_text=True)

    if score is None:
        score_fill = PatternFill('solid', start_color='D9D9D9')
    elif score >= 8:
        score_fill = PatternFill('solid', start_color='C6EFCE')
    elif score >= 6:
        score_fill = PatternFill('solid', start_color='FFEB9C')
    else:
        score_fill = PatternFill('solid', start_color='FFC7CE')

    with FileLock(SCORESHEET_LOCK, timeout=30):
        _write_excel_row(student_name, student_roll, student_email, subject, difficulty, score, grade,
                          strengths, improvements, exchanges, project_name,
                          thin, border, header_font, header_fill, center,
                          left, score_fill)
    return SCORESHEET_FILE

def _ensure_column(ws, position, header, header_font, header_fill, center, border, width):
    """Insert `header` as a new column at `position` if a sheet saved before
    that column existed doesn't have it yet. Callers must ensure columns in
    left-to-right order so each insertion doesn't shift a column already
    ensured back out of place."""
    if ws.cell(row=1, column=position).value != header:
        ws.insert_cols(position)
        cell = ws.cell(row=1, column=position, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = center
        cell.border = border
        ws.column_dimensions[get_column_letter(position)].width = width

def _write_excel_row(student_name, student_roll, student_email, subject, difficulty, score, grade,
                      strengths, improvements, exchanges, project_name,
                      thin, border, header_font, header_fill, center,
                      left, score_fill):
    """The actual read-modify-write, called only while SCORESHEET_LOCK is held."""
    if os.path.exists(SCORESHEET_FILE):
        wb = load_workbook(SCORESHEET_FILE)
        ws = wb.active

        # One-time migration for sheets saved before Roll No / Email existed
        # as columns, so old rows and new rows stay aligned under the same
        # headers instead of every later column being off by one or two.
        _ensure_column(ws, 4, "Roll No", header_font, header_fill, center, border, 16)
        _ensure_column(ws, 5, "Email", header_font, header_fill, center, border, 26)

        # A previous save appends a "Total Students" summary row a couple of
        # rows below the last student. Remove it before appending the next
        # student, otherwise every save leaves another stale summary row
        # scattered through the data instead of one at the bottom.
        for r in range(ws.max_row, 1, -1):
            if ws.cell(row=r, column=1).value == "Total Students":
                ws.delete_rows(r, ws.max_row - r + 1)
                break
        next_row = ws.max_row + 1
    else:
        wb = Workbook()
        ws = wb.active
        ws.title = "Viva Scores"

        headers = ["S.No", "Date", "Student Name", "Roll No", "Email", "Subject",
                   "Difficulty", "Project File", "Score (/10)",
                   "Grade", "Exchanges", "Strengths", "Areas for Improvement"]
        col_widths = [6, 18, 20, 16, 26, 22, 12, 28, 12, 20, 10, 40, 40]

        for col, (h, w) in enumerate(zip(headers, col_widths), 1):
            cell = ws.cell(row=1, column=col, value=h)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = center
            cell.border = border
            ws.column_dimensions[get_column_letter(col)].width = w

        ws.row_dimensions[1].height = 30
        ws.freeze_panes = "A2"
        next_row = 2

    row_data = [
        next_row - 1,
        datetime.now().strftime("%d-%b-%Y %H:%M"),
        student_name or "Unknown",
        student_roll or "—",
        student_email or "—",
        subject,
        difficulty,
        project_name,
        score if score is not None else "Pending",
        grade,
        exchanges,
        strengths or "—",
        improvements or "—"
    ]

    for col, value in enumerate(row_data, 1):
        cell = ws.cell(row=next_row, column=col, value=value)
        cell.font = Font(name='Arial', size=10)
        cell.border = border
        cell.alignment = center if col in [1, 9, 10, 11] else left
        if col == 9:
            cell.fill = score_fill
            cell.font = Font(name='Arial', size=10, bold=True)
        elif next_row % 2 == 0:
            cell.fill = PatternFill('solid', start_color='EBF3FB')

    ws.row_dimensions[next_row].height = 40

    # Summary row
    summary_row = ws.max_row + 2
    for col, (label, formula) in enumerate([
        ("Total Students", f'=COUNTA(C2:C{next_row})'),
        ("Avg Score", f'=IFERROR(AVERAGEIF(I2:I{next_row},"<>Pending",I2:I{next_row}),"-")'),
        ("Highest", f'=IFERROR(MAX(I2:I{next_row}),"-")'),
        ("Lowest", f'=IFERROR(MINIFS(I2:I{next_row},I2:I{next_row},"<>Pending"),"-")')
    ], start=1):
        label_cell = ws.cell(row=summary_row, column=col*2-1, value=label)
        label_cell.font = Font(name='Arial', bold=True, color='FFFFFF', size=10)
        label_cell.fill = PatternFill('solid', start_color='2E75B6')
        label_cell.alignment = center

        val_cell = ws.cell(row=summary_row, column=col*2, value=formula)
        val_cell.font = Font(name='Arial', bold=True, size=10)
        val_cell.alignment = center

    wb.save(SCORESHEET_FILE)
    return SCORESHEET_FILE

# --- Prevent a student from re-attempting the viva with the same link ---
def get_local_completed_rolls():
    """Returns the set of normalized Roll Numbers that already have a viva
    recorded in the LOCAL scoresheet on this running app instance. This
    resets if Streamlit Cloud restarts the app (a redeploy, or the container
    recycling after long inactivity) — kept only as an extra safety net
    alongside the durable Google Sheet check below.
    """
    if not os.path.exists(SCORESHEET_FILE):
        return set()
    try:
        with FileLock(SCORESHEET_LOCK, timeout=15):
            wb = load_workbook(SCORESHEET_FILE, read_only=True)
            ws = wb.active
            header_row = next(ws.iter_rows(min_row=1, max_row=1, values_only=True), ())
            if "Roll No" not in header_row:
                return set()
            roll_col = header_row.index("Roll No")
            rolls = set()
            for row in ws.iter_rows(min_row=2, values_only=True):
                value = row[roll_col] if roll_col < len(row) else None
                if value and str(value).strip():
                    rolls.add(str(value).strip().lower())
            return rolls
    except Exception:
        # Fail OPEN: an unreadable/locked scoresheet shouldn't itself block
        # a legitimate student from starting. Worst case here is a rare
        # missed duplicate, not the whole class getting locked out.
        return set()

@st.cache_data(ttl=20, show_spinner=False)
def get_remote_completed_rolls():
    """Reads the DURABLE list of Roll Numbers already recorded in the Google
    Sheet (via a GET request to the same Apps Script Web App the score
    webhook already posts to). Unlike the local file, this survives an app
    restart, so it's the authoritative check. Cached for a short window
    (20s) so every student's page render doesn't hit the Apps Script quota —
    a student who just finished may take up to ~20s to show up as blocked
    for someone else reloading the link, which is an acceptable trade-off.
    """
    webhook_url = st.secrets.get("GSHEETS_WEBHOOK_URL") or os.environ.get("GSHEETS_WEBHOOK_URL")
    if not webhook_url:
        return set()
    try:
        response = requests.get(webhook_url, timeout=10)
        data = response.json()
        return {str(r).strip().lower() for r in data.get("rolls", []) if r is not None and str(r).strip()}
    except Exception:
        # Fail OPEN here too: a network hiccup or a Sheet script that hasn't
        # been updated with the doGet handler yet shouldn't block students —
        # the local check below still catches same-session repeats.
        return set()

def get_completed_rolls():
    """Union of the durable Google Sheet record and the local scoresheet —
    a student is blocked if EITHER source already shows a completed viva
    for their Roll Number."""
    return get_local_completed_rolls() | get_remote_completed_rolls()

# --- Grade helper ---
def get_grade(score):
    if score is None:
        return "N/A"
    elif score >= 9:
        return "O (Outstanding)"
    elif score >= 8:
        return "A+ (Excellent)"
    elif score >= 7:
        return "A (Very Good)"
    elif score >= 6:
        return "B (Good)"
    elif score >= 5:
        return "C (Average)"
    else:
        return "F (Fail)"

# --- Sidebar ---
with st.sidebar:
    st.header("⚙️ Viva Settings")
    
    # Subject selection or lock
    if VIVA_SUBJECT:
        subject = st.text_input("Subject (Locked)", value=VIVA_SUBJECT, disabled=True)
    else:
        subject = st.selectbox("Subject", AVAILABLE_SUBJECTS)
        
    # Difficulty selection or lock
    if VIVA_DIFFICULTY:
        difficulty = st.text_input("Difficulty (Locked)", value=VIVA_DIFFICULTY, disabled=True)
    else:
        difficulty = st.selectbox("Difficulty", ["Easy", "Standard", "Rigorous"])
        
    student_name = st.text_input("Student Name", placeholder="Enter full name...")
    student_roll = st.text_input("Student Roll", placeholder="Enter roll number...")
    student_email = st.text_input("Student Email", placeholder="Enter email address...")
    if student_email and "@" not in student_email:
        st.warning("That doesn't look like a valid email address.")

    # Block a repeat attempt with the same Roll Number on this same link.
    # Roll Number is now required (not just Name) precisely because it's
    # the key this check relies on.
    normalized_roll = (student_roll or "").strip().lower()
    already_done = bool(normalized_roll) and normalized_roll in get_completed_rolls()
    if already_done:
        st.error(
            "🚫 A completed viva is already on record for this Roll Number "
            "on this link. If this is a mistake, contact your faculty."
        )

    st.divider()
    st.subheader("🔊 Voice Settings")
    voice_output = st.toggle("🔊 Examiner speaks aloud", value=True,
                             help="Examiner's questions will be read out loud via the browser text-to-speech API")
    voice_input = st.toggle("🎙️ Use microphone for answers", value=True,
                            help="Speak your answers using your device's microphone")
    if voice_output or voice_input:
        st.success("🎤 Oral viva mode is ON")
    else:
        st.info("📝 Text-only mode")

    st.divider()
    st.subheader("📄 Upload Project")
    uploaded_file = st.file_uploader(
        "Upload your project report",
        type=["pdf", "docx"],
        help="Questions will be based entirely on your project"
    )

    start_btn = st.button(
        "🎓 Start Viva", type="primary",
        disabled=(uploaded_file is None or not student_name or not student_roll or already_done)
    )
    if not student_name:
        st.warning("Enter student name to begin.")
    elif not student_roll:
        st.warning("Enter roll number to begin.")
    elif already_done:
        pass  # the error above already explains why the button is disabled
    elif uploaded_file is None:
        st.warning("Upload project to begin.")

# --- Session state init ---
for key, default in [
    ("messages", []),
    ("viva_started", False),
    ("exchange_count", 0),
    ("project_text", ""),
    ("viva_ended", False),
    ("score_saved", False),
    ("final_score", None),
    ("final_grade", ""),
    ("project_name", ""),
    ("listening", False),
    ("closing_message", ""),
    ("saved_path", ""),
    ("processed_audio_ids", set()),
    ("last_spoken_index", -1),
    ("cheated_detected", False),
    ("timeout_triggered", False),
    ("viva_start_time", None),
]:
    if key not in st.session_state:
        st.session_state[key] = default

# --- Active Focus & Timer Monitor (Sidebar Injection) ---
if st.session_state.viva_started and not st.session_state.viva_ended and VIVA_TIME_LIMIT_MINUTES > 0:
    elapsed = int(time.time() - st.session_state.viva_start_time)
    remaining_seconds = max(0, VIVA_TIME_LIMIT_MINUTES * 60 - elapsed)
    
    with st.sidebar:
        st.divider()
        # Render the controller iframe
        viva_signal = render_viva_controller(remaining_seconds)
        
        # Monitor signals returned from client-side JS
        if viva_signal == "cheated":
            st.session_state.cheated_detected = True
            st.session_state.viva_ended = True
            st.rerun()
        elif viva_signal == "timeout" or remaining_seconds <= 0:
            st.session_state.timeout_triggered = True
            st.session_state.viva_ended = True
            st.rerun()

# --- Start viva ---
if (start_btn and not st.session_state.viva_started and uploaded_file
        and student_name and student_roll and not already_done):
    st.session_state.project_name = uploaded_file.name
    with st.spinner("📖 Reading your project..."):
        project_text = extract_text(uploaded_file)
        st.session_state.project_text = project_text

    st.session_state.viva_start_time = time.time()

    # Precomputed as plain strings (rather than nested f-string expressions)
    # to keep the big SYSTEM_PROMPT f-string below readable.
    mandatory_questions_block = ""
    if VIVA_MANDATORY_QUESTIONS:
        numbered = "\n".join(
            f"{i + 1}. {q}" for i, q in enumerate(VIVA_MANDATORY_QUESTIONS)
        )
        mandatory_questions_block = (
            "\nSUBJECT-SPECIFIC QUESTIONS TO INCLUDE:\n"
            "You MUST ask each of the following questions at some point during "
            "this viva (you may phrase them more naturally in your own voice, "
            "but keep their meaning intact). Treat each one as ONE of your "
            "one-question-at-a-time turns, spread out among the project-"
            "specific questions rather than asked back-to-back:\n"
            f"{numbered}\n"
        )

    SYSTEM_PROMPT = f"""You are a strict but fair oral viva examiner for a PGDM {subject} course at Great Lakes Institute of Management.

Student name: {student_name}
Roll No: {student_roll}
Difficulty level: {difficulty}
{f'''
ADDITIONAL FACULTY INSTRUCTIONS — follow these when choosing and phrasing
questions, in addition to (not instead of) the rules below:
{VIVA_CUSTOM_INSTRUCTIONS.strip()}
''' if VIVA_CUSTOM_INSTRUCTIONS.strip() else ""}
{mandatory_questions_block}
The student has submitted the following project. Base ALL your questions ONLY on this project:

--- PROJECT START ---
{truncate(project_text)}
--- PROJECT END ---

CRITICAL FORMATTING RULE — READ CAREFULLY:
- Every reply you send must contain EXACTLY ONE question, and nothing more.
- Never number or list multiple questions ("1)... 2)..."). Never use "also",
  "additionally", "and also tell me", or similar to tack a second question
  onto the same reply.
- Your reply should contain AT MOST ONE question mark ("?"). If you notice
  you have written more than one question, delete every question except the
  first before sending your reply.
- If you want to test the student on several concepts, ask about only ONE of
  them now. Wait for their answer. You will get another turn to ask about the
  next one — do not rush multiple concepts into a single message.

Your rules:
- Ask ONE question at a time (see CRITICAL FORMATTING RULE above — this is
  the most important rule in this prompt).
- Keep responses concise — this is a spoken oral viva.
- Focus on the following two-phase examination flow:

  PHASE 1: CONCEPT AUTHENTICATION (First 2-3 questions)
  Your FIRST job is to authenticate the student: confirm they genuinely know the
  concepts, theories, models, frameworks and terminology that appear in THEIR OWN
  report. Identify the key concepts actually named in the project text above and
  test the student on them, ONE CONCEPT PER TURN.
  - Pick ONE specific term/model/framework that appears in the report and ask the
    student to DEFINE it in their own words. Do this in a single, focused question.
  - On a LATER turn, ask how that specific concept was applied in their project
    and why they chose it — as its own separate question, not combined with the
    definition question.
  - Across several separate turns (not one combined message), require the student
    to correctly explain at least TWO key concepts from their report before you
    move on to Phase 2.
  - If the student cannot define or explain the core concepts written in their own
    report, treat this as a red flag for authenticity, note it explicitly, weight
    the final score down accordingly, and continue with stricter questioning.

  PHASE 2: PROJECT DEEP DIVE (Remaining questions)
  Once the concept authentication is done, probe their specific methodology, findings, data collection, and recommendations. 
  - Challenge weak arguments, assumptions, or inconsistencies in their data.
  - Check their knowledge of their own analysis.

- After every 5 exchanges give a brief mid-viva remark (one or two sentences),
  then still ask only ONE question in that same reply — the remark does not
  give you license to ask more than one question.
- After {VIVA_TOTAL_QUESTIONS} exchanges, end the viva with EXACTLY this format:

VIVA COMPLETE
Score: X/10
Strengths: [2-3 specific points]
Areas for Improvement: [2-3 specific points]
Recommended Topics: [list]

Begin now by greeting {student_name} warmly and starting Phase 1 (Concept Authentication) by asking your first question about a key concept in their project report."""

    st.session_state.messages = [{"role": "system", "content": SYSTEM_PROMPT}]

    with st.spinner("Examiner is preparing..."):
        reply = chat_with_llm(st.session_state.messages)

    if reply is None:
        # chat_with_llm already showed the error. Leave viva_started False so
        # the student just sees the Start button again and can retry.
        st.stop()

    st.session_state.messages.append({"role": "assistant", "content": reply})
    st.session_state.viva_started = True

# --- Project preview in sidebar ---
if st.session_state.project_text:
    with st.sidebar:
        st.divider()
        st.caption(f"📋 {st.session_state.project_name}")
        st.caption(f"{len(st.session_state.project_text):,} characters loaded")
        with st.expander("Preview"):
            st.write(st.session_state.project_text[:400] + "...")

# --- Display chat ---
for msg in st.session_state.messages:
    if msg["role"] == "system":
        continue
    with st.chat_message("assistant" if msg["role"] == "assistant" else "user"):
        st.markdown(msg["content"])

# --- Request a final summary from the LLM (used when the exchange cap is hit
#     but the model hasn't produced the VIVA COMPLETE block yet). ---
def request_final_summary():
    closing_user_turn = (
        "The viva is now complete. Please immediately produce the final assessment "
        "in EXACTLY this format, with no preamble or follow-up questions:\n\n"
        "VIVA COMPLETE\n"
        "Score: X/10  (use a number from 0 to 10)\n"
        "Strengths: [2-3 specific points based on the student's actual answers]\n"
        "Areas for Improvement: [2-3 specific points]\n"
        "Recommended Topics: [list]"
    )
    st.session_state.messages.append({"role": "user", "content": closing_user_turn})
    summary = chat_with_llm(st.session_state.messages)
    if summary is None:
        # Roll back the closing nudge so a retry starts from a clean state
        # instead of stacking up duplicate "wrap up now" turns.
        st.session_state.messages.pop()
        st.stop()
    st.session_state.messages.append({"role": "assistant", "content": summary})
    return summary

# --- Handle student response ---
def handle_response(user_text, via_voice=False):
    st.session_state.messages.append({"role": "user", "content": user_text})
    st.session_state.exchange_count += 1

    with st.chat_message("user"):
        st.markdown(f"🎙️ *{user_text}*" if via_voice else user_text)

    with st.chat_message("assistant"):
        with st.spinner("Examiner is responding..."):
            reply = chat_with_llm(st.session_state.messages)
        if reply is None:
            # Roll back this turn so the student's exchange count and chat
            # history look exactly as if they hadn't submitted yet — they
            # can just answer again once the API is free.
            st.session_state.messages.pop()
            st.session_state.exchange_count -= 1
            st.stop()
        st.session_state.messages.append({"role": "assistant", "content": reply})
        st.markdown(reply)

    st.sidebar.metric("Exchanges", st.session_state.exchange_count)

    should_end = ("VIVA COMPLETE" in reply) or (st.session_state.exchange_count >= VIVA_TOTAL_QUESTIONS)
    if should_end:
        final_text = reply
        if "VIVA COMPLETE" not in reply:
            with st.chat_message("assistant"):
                with st.spinner("📋 Preparing final assessment..."):
                    final_text = request_final_summary()
                st.markdown(final_text)

        st.session_state.viva_ended = True
        st.session_state.final_score = parse_score(final_text)
        st.session_state.final_grade = get_grade(st.session_state.final_score)
        st.session_state.closing_message = final_text

# --- Input area (voice + text) ---
if st.session_state.viva_started and not st.session_state.viva_ended:
    # Visible status banner so user always sees whether voice is active
    if voice_input or voice_output:
        bits = []
        if voice_output:
            bits.append("🔊 examiner speaks")
        if voice_input:
            bits.append("🎙️ browser mic enabled")
        st.caption("Voice mode: " + " · ".join(bits))

    # Browser microphone input using Streamlit 1.39+ st.audio_input
    if voice_input:
        audio_file = st.audio_input("🎙️ Record your answer", key="viva_audio")
        if audio_file is not None:
            file_id = getattr(audio_file, "id", None) or hash(audio_file.getvalue())
            if file_id not in st.session_state.processed_audio_ids:
                st.session_state.processed_audio_ids.add(file_id)
                with st.spinner("🎙️ Transcribing speech..."):
                    try:
                        transcription = client.audio.transcriptions.create(
                            file=(audio_file.name, audio_file.getvalue()),
                            model="whisper-large-v3",
                        )
                        spoken_text = transcription.text.strip()
                        if spoken_text:
                            handle_response(spoken_text, via_voice=True)
                        else:
                            st.warning("Could not transcribe any speech. Please try speaking again.")
                    except Exception as e:
                        st.error(f"Groq Whisper transcription failed: {e}")

    # Text input fallback (always visible)
    typed = st.chat_input("Or type your answer here...")
    if typed:
        handle_response(typed, via_voice=False)

# --- Handle termination cases ---
if st.session_state.viva_ended:
    if st.session_state.get("cheated_detected", False) and not st.session_state.score_saved:
        st.session_state.final_score = 0.0
        st.session_state.final_grade = "F (Academic Dishonesty)"
        st.session_state.closing_message = "VIVA TERMINATED: Student switched tabs or minimized the exam window."
        
    elif st.session_state.get("timeout_triggered", False) and not st.session_state.score_saved:
        with st.spinner("⏳ Time's up! Generating final assessment..."):
            final_text = request_final_summary()
        st.session_state.final_score = parse_score(final_text)
        st.session_state.final_grade = get_grade(st.session_state.final_score)
        st.session_state.closing_message = final_text

# --- Viva ended screen and saving ---
if st.session_state.viva_ended:
    st.divider()
    if st.session_state.get("cheated_detected", False):
        st.error("🚨 VIVA TERMINATED: Tab switching or window minimization detected. This incident has been logged.")
    elif st.session_state.get("timeout_triggered", False):
        st.warning("⏱️ Time limit reached! The viva has been automatically submitted.")
    else:
        st.subheader("🏁 Viva Complete")

    # ---- AUTO-SAVE the scoresheet immediately ----
    if not st.session_state.score_saved:
        closing = st.session_state.closing_message or (
            st.session_state.messages[-1]["content"] if st.session_state.messages else ""
        )
        strengths, improvements = parse_feedback(closing)
        
        # Override values if cheated
        if st.session_state.get("cheated_detected", False):
            strengths = "N/A - Terminated for cheating"
            improvements = "Switched tabs or minimized browser tab during active exam"
            
        try:
            filepath = save_to_excel(
                student_name=student_name,
                student_roll=student_roll,
                student_email=student_email,
                subject=subject,
                difficulty=difficulty,
                score=st.session_state.final_score,
                grade=st.session_state.final_grade,
                strengths=strengths,
                improvements=improvements,
                exchanges=st.session_state.exchange_count,
                project_name=st.session_state.project_name,
            )
            st.session_state.score_saved = True
            st.session_state.saved_path = filepath
            st.success(f"✅ Scoresheet auto-saved locally to:\n`{filepath}`")
        except Exception as e:
            st.error(f"⚠️ Local auto-save failed: {e}")

        # Post to Google Sheets if webhook is configured
        gs_saved = save_to_google_sheets(
            student_name=student_name,
            student_roll=student_roll,
            student_email=student_email,
            subject=subject,
            difficulty=difficulty,
            score=st.session_state.final_score,
            grade=st.session_state.final_grade,
            strengths=strengths,
            improvements=improvements,
            exchanges=st.session_state.exchange_count,
            project_name=st.session_state.project_name,
        )
        if gs_saved:
            st.success("📊 Score successfully posted to Google Sheets!")

    # ---- Score / grade display ----
    col1, col2 = st.columns(2)
    with col1:
        if st.session_state.final_score is not None:
            st.metric("Final Score", f"{st.session_state.final_score}/10")
        else:
            st.metric("Final Score", "—")
    with col2:
        st.metric("Grade", st.session_state.final_grade)

    # ---- Manual override if the LLM still didn't give a numeric score ----
    if st.session_state.final_score is None:
        st.warning("The examiner did not return a numeric score. You can set one manually below.")
        manual = st.number_input(
            "Manual final score (0-10)", min_value=0.0, max_value=10.0,
            step=0.5, value=7.0, key="manual_score"
        )
        if st.button("Apply manual score and re-save"):
            st.session_state.final_score = float(manual)
            st.session_state.final_grade = get_grade(st.session_state.final_score)
            closing = st.session_state.closing_message or ""
            strengths, improvements = parse_feedback(closing)
            
            if st.session_state.get("cheated_detected", False):
                strengths = "N/A - Terminated for cheating"
                improvements = "Switched tabs or minimized browser tab during active exam"
                
            filepath = save_to_excel(
                student_name=student_name, student_roll=student_roll, student_email=student_email,
                subject=subject, difficulty=difficulty,
                score=st.session_state.final_score, grade=st.session_state.final_grade,
                strengths=strengths, improvements=improvements,
                exchanges=st.session_state.exchange_count,
                project_name=st.session_state.project_name,
            )
            st.session_state.saved_path = filepath
            st.success(f"✅ Updated and saved to `{filepath}`")

            # Post manual override to Google Sheets
            save_to_google_sheets(
                student_name=student_name,
                student_roll=student_roll,
                student_email=student_email,
                subject=subject,
                difficulty=difficulty,
                score=st.session_state.final_score,
                grade=st.session_state.final_grade,
                strengths=strengths,
                improvements=improvements,
                exchanges=st.session_state.exchange_count,
                project_name=st.session_state.project_name,
            )
            st.rerun()

    # ---- Download button kept as a BACKUP per your request ----
    if st.session_state.score_saved and os.path.exists(SCORESHEET_FILE):
        with open(SCORESHEET_FILE, "rb") as f:
            st.download_button(
                label="⬇️ Download Scoresheet (backup copy)",
                data=f,
                file_name="GLIM_Viva_Scores.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
        st.caption(f"Master file on disk: `{st.session_state.saved_path or SCORESHEET_FILE}`")

elif not st.session_state.viva_started:
    st.info("👈 Fill in settings and upload project to begin.")

# --- Browser Text-to-Speech (TTS) Trigger ---
if st.session_state.viva_started and voice_output:
    # Get all assistant messages
    assistant_msgs = [msg for msg in st.session_state.messages if msg["role"] == "assistant"]
    if assistant_msgs:
        last_msg = assistant_msgs[-1]
        last_msg_index = len(assistant_msgs) - 1
        
        # Only speak if it hasn't been spoken yet
        if st.session_state.get("last_spoken_index", -1) != last_msg_index:
            st.session_state.last_spoken_index = last_msg_index
            text_to_speak = last_msg["content"]
            
            # If the viva has ended or it contains completion tags, say a short wrap up
            if st.session_state.viva_ended or "VIVA COMPLETE" in text_to_speak:
                text_to_speak = "The viva is now complete. I have generated your final score and assessment details. Thank you."
                
            # Clean up text for JavaScript
            escaped_text = (
                text_to_speak
                .replace('\\', '\\\\')
                .replace('"', '\\"')
                .replace("'", "\\'")
                .replace('\n', ' ')
            )
            
            html_code = f"""
            <script>
            if (window.speechSynthesis) {{
                window.speechSynthesis.cancel();
                setTimeout(function() {{
                    var utterance = new SpeechSynthesisUtterance("{escaped_text}");
                    utterance.rate = 1.05;
                    window.speechSynthesis.speak(utterance);
                }}, 50);
            }}
            </script>
            """
            components.html(html_code, height=0)
